(()=>{
const $=id=>document.getElementById(id),L=k=>{try{return JSON.parse(localStorage.getItem(k))}catch(e){return null}},S=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
let pt=L('sx_pt')||{},fav=L('sx_fav')||[],pf=L('sx_pf')||[],cmp=[],tab='All';
window.fv=s=>fav.includes(s);
const st=document.createElement('style');st.textContent=`.nav{display:flex;gap:6px;overflow-x:auto;position:sticky;top:0;z-index:20;background:var(--bg);padding:8px 0;margin-bottom:8px}.nav .ch{white-space:nowrap;border-radius:999px}.stb{cursor:pointer;margin-left:8px;font-size:15px}.grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.mr{cursor:pointer}#cmpb{position:fixed;left:16px;bottom:16px;z-index:60;display:none;background:var(--a);color:#fff;border:0;border-radius:999px;padding:12px 18px;font-weight:700}.card{backdrop-filter:blur(8px);box-shadow:0 4px 24px #0002}table.t{width:100%;border-collapse:collapse;font-size:13px}table.t td,table.t th{padding:6px;border-bottom:1px solid var(--b);text-align:left}`;document.head.append(st);
const mf=document.createElement('link');mf.rel='manifest';mf.href='manifest.json';document.head.append(mf);
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
const ov=r=>{const p=r.prof||{},m=p.mx||{},pos=p.hi>p.lo?(r.p-p.lo)/(p.hi-p.lo):.5,h=r.hist||[];
 const s=[r.chg>0,(m['13WeekPriceReturnDaily']??0)>0,r.sent>0,pos>.5,h.length>1&&h[h.length-1]>=h[0]];
 const l=[(m.revenueGrowthTTMYoy??0)>10,(m.epsGrowthTTMYoy??0)>10,(m.netProfitMarginTTM??0)>0,(m.roeTTM??0)>12,r.an?(r.an.strongBuy+r.an.buy)>(r.an.hold+r.an.sell+r.an.strongSell):false,(m['totalDebt/totalEquityQuarterly']??9)<1.5];
 return[s.filter(Boolean).length/s.length,l.filter(Boolean).length/l.length]};
const tg=v=>v>=.6?'<b class="up">▲ Bullish</b>':v<=.3?'<b class="dn">▼ Bearish</b>':'<b>● Neutral</b>';
window.ol=r=>{const[a,b]=ov(r);return`<div class="e">Short-term ${tg(a)} · Long-term ${tg(b)}</div>`};
const mini=r=>`<div class="row mr" data-s="${esc(r.s)}" style="padding:6px 0;border-bottom:1px solid var(--b)"><b>${esc(r.s)}</b><span>$${r.p.toFixed(2)} <b class="${r.chg>=0?'up':'dn'}">${r.chg>=0?'+':''}${r.chg.toFixed(1)}%</b> <span class="m">${r.rating||''}</span></span></div>`;
const box=(t,h)=>`<div class="card"><h3 style="margin:0 0 6px">${t}</h3>${h||'<span class="m">Nothing yet</span>'}</div>`;
const V={
'Overview':()=>{const u=D._all,sc={};u.forEach(r=>(sc[r.sec]=sc[r.sec]||[]).push(r.chg));
 const rows=Object.entries(sc).map(([k,v])=>[k,v.reduce((a,b)=>a+b,0)/v.length,v.length]).sort((a,b)=>b[1]-a[1]);
 const top=(k,i)=>[...u].sort((a,b)=>ov(b)[i]-ov(a)[i]||b.score-a.score).slice(0,6).map(mini).join('');
 return`<div class="grid2">${box('Sectors today',rows.map(x=>`<div class="row" style="padding:5px 0"><span>${esc(x[0])} <span class="m">(${x[2]})</span></span><b class="${x[1]>=0?'up':'dn'}">${x[1]>=0?'+':''}${x[1].toFixed(2)}%</b></div>`).join(''))}${box('Top gainers',[...u].sort((a,b)=>b.chg-a.chg).slice(0,6).map(mini).join(''))}${box('Top losers',[...u].sort((a,b)=>a.chg-b.chg).slice(0,6).map(mini).join(''))}${box('Best short-term outlook',top(0,0))}${box('Best long-term outlook',top(0,1))}${box('Market headlines',(D.market||[]).map(n=>`<a href="${esc(n.u)}" target="_blank" rel="noopener">${esc(n.h)}</a>`).join(''))}</div>`},
'My list':()=>{const a=fav.map(s=>D._all.find(r=>r.s==s)).filter(Boolean);return a.length?`<div class="grid">${a.map(card).join('')}</div>`:'<p class="m">Tap ☆ on any stock card to add it here. Saved on this device only.</p>'},
'Portfolio':()=>{let tc=0,tv=0;const rows=pf.map((h,i)=>{const r=D._all.find(x=>x.s==h.s);if(!r)return'';const c=h.q*h.c,v=h.q*r.p;tc+=c;tv+=v;const g=v-c;return`<tr class="mr" data-s="${esc(h.s)}"><td><b>${esc(h.s)}</b></td><td>${h.q}</td><td>$${h.c}</td><td>$${r.p.toFixed(2)}</td><td class="${g>=0?'up':'dn'}">${g>=0?'+':''}$${g.toFixed(0)} (${(g/c*100).toFixed(1)}%)</td><td>${r.rating}</td><td><span class="x" data-rm="${i}" style="cursor:pointer">✕</span></td></tr>`}).join('');
 return`<div class="card"><div class="bar"><input id="pt" placeholder="Ticker"><input id="pq" placeholder="Shares" inputmode="decimal"><input id="pc" placeholder="Buy price" inputmode="decimal"><button class="ch on" id="pa">Add</button></div><table class="t"><tr><th>Stock</th><th>Qty</th><th>Cost</th><th>Now</th><th>P/L</th><th>Rating</th><th></th></tr>${rows}</table><p><b>Total: $${tv.toFixed(0)} <span class="${tv>=tc?'up':'dn'}">(${tc?((tv-tc)/tc*100).toFixed(1):0}%)</span></b></p><p class="m">Saved on this device only.</p></div>`},
'Calendar':()=>{const a=D._all.filter(r=>r.earn).sort((x,y)=>x.earn.localeCompare(y.earn));return`<div class="card">${a.map(r=>`<div class="row mr" data-s="${esc(r.s)}" style="padding:6px 0;border-bottom:1px solid var(--b)"><span><b>${esc(r.earn)}</b> · ${esc(r.s)}</span><span class="m">$${r.p.toFixed(2)} · ${r.rating}</span></div>`).join('')||'<span class="m">No earnings dates yet</span>'}</div>`},
'ETFs':()=>`<div class="grid">${(D.etfs||[]).map(e=>`<div class="card"><div class="row"><b class="s">${esc(e.s)}</b><span>$${e.p.toFixed(2)} <b class="${e.chg>=0?'up':'dn'}">${e.chg>=0?'+':''}${e.chg.toFixed(2)}%</b></span></div>${spark(e.hist)}</div>`).join('')||'<p class="m">ETF data arrives after the next update.</p>'}</div>`,
'Screener':()=>`<div class="card"><h3 style="margin:0 0 6px">Scan any stock</h3><div class="bar"><input id="sq" placeholder="Ticker, e.g. NVDA"><button class="ch on" id="sb">Scan</button></div><h3 style="margin:10px 0 6px">Rule filter</h3><input id="sr" style="width:100%" placeholder="price<50 and pe<25 and growth>15 and rating=buy"><button class="ch on" id="srun" style="margin-top:8px">Run</button><div id="so2" style="margin-top:8px"></div><div class="m">Fields: price, chg, score, pe, growth, epsgrowth, margin, roe, debt, beta, sent, sector, rating, halal. Operators: &lt; &gt; &lt;= &gt;= = with and / or.</div></div>`,
'Track record':()=>{const t=D.track||[],m=Object.fromEntries(D._all.map(r=>[r.s,r.p]));return`<div class="card"><p class="m">Average return of each day's top 20 picks, from the day they were picked to now. Today's picks start at 0%.</p><table class="t"><tr><th>Date</th><th>Picks</th><th>Avg return</th></tr>${[...t].reverse().map(e=>{const rs=e.p.filter(x=>m[x.s]).map(x=>(m[x.s]/x.p-1)*100),a=rs.length?rs.reduce((x,y)=>x+y,0)/rs.length:0;return`<tr><td>${e.d}</td><td>${rs.length}</td><td class="${a>=0?'up':'dn'}">${a>=0?'+':''}${a.toFixed(2)}%</td></tr>`}).join('')}</table></div>`}};
function render(){const n=document.querySelector('.nav');if(!n){document.getElementById('app').insertAdjacentHTML('beforebegin','<div class="nav" id="nv"></div>');document.getElementById('app').insertAdjacentHTML('afterend','<div id="view"></div>');}
 $('nv').innerHTML=['All',...Object.keys(V)].map(k=>`<button class="ch ${k==tab?'on':''}" data-t="${k}">${k}</button>`).join('');
 if(!$('hits'))$('nv').insertAdjacentHTML('afterend','<div id="hits"></div>');$('hits').innerHTML=hits().map(h=>`<div class="al mr" data-s="${h[0]}"><b>${h[0]}</b> ${h[1]}</div>`).join('');$('app').style.display=tab=='All'?'':'none';const keep=tab=='Screener'&&$('view').dataset.k=='S';if(!keep)$('view').innerHTML=tab=='All'||!D?'':V[tab]();$('view').dataset.k=tab=='Screener'?'S':'';
 $('cmpb').style.display=cmp.length>1?'block':'none';$('cmpb').textContent='⚖ Compare ('+cmp.length+')'}
document.body.insertAdjacentHTML('beforeend','<button id="cmpb"></button>');
const od=window.draw;window.draw=function(){od();render()};render();
document.addEventListener('click',e=>{const t=e.target,b=t.closest('.stb');
 if(t.dataset.t){tab=t.dataset.t;render();return}
 if(b){e.stopPropagation();if(b.dataset.f){const s=b.dataset.f;fav=fav.includes(s)?fav.filter(x=>x!=s):[...fav,s];S('sx_fav',fav);draw()}else{const s=b.dataset.c;cmp=cmp.includes(s)?cmp.filter(x=>x!=s):[...cmp,s].slice(-3);render()}return}
 if(t.id=='pa'){const s=$('pt').value.trim().toUpperCase(),q=+$('pq').value,c=+$('pc').value;if(s&&q>0&&c>0){pf.push({s,q,c});S('sx_pf',pf);render()}return}
 if(t.dataset.rm!=null){pf.splice(+t.dataset.rm,1);S('sx_pf',pf);render();return}
 if(t.id=='sb'){scan($('sq').value);return}if(t.id=='srun'){runRule();return}if(t.id=='cmpb'){const a=cmp.map(s=>D._all.find(r=>r.s==s)).filter(Boolean),R=(n,fn)=>`<tr><th>${n}</th>${a.map(r=>`<td>${fn(r)}</td>`).join('')}</tr>`,M=r=>(r.prof||{}).mx||{};
  $('dt').textContent='Compare';$('db').innerHTML=`<table class="t"><tr><th></th>${a.map(r=>`<th>${esc(r.s)}</th>`).join('')}</tr>${R('Price',r=>'$'+r.p.toFixed(2))}${R('Today',r=>r.chg.toFixed(2)+'%')}${R('Score',r=>r.score+'/10')}${R('Rating',r=>r.rating)}${R('Short-term',r=>tg(ov(r)[0]))}${R('Long-term',r=>tg(ov(r)[1]))}${R('P/E',r=>f((r.prof||{}).pe,1))}${R('Revenue growth',r=>f(M(r).revenueGrowthTTMYoy,1,'%'))}${R('Net margin',r=>f(M(r).netProfitMarginTTM,1,'%'))}${R('ROE',r=>f(M(r).roeTTM,1,'%'))}${R('Debt/equity',r=>f(M(r)['totalDebt/totalEquityQuarterly']))}${R('Sector',r=>esc(r.sec))}</table>`;$('dm').style.display='block';return}
 const mr=t.closest('#view .mr,#view .card,#hits .mr');if(mr&&mr.dataset.s&&!t.closest('a'))deepScan(mr.dataset.s)},true);
const XS="Fundamentals:40:10,Business model:20:0,Growth engine:35:0,Future catalysts:35:0,Earnings and guidance:26:3,Management:24:2,Competition:21:0,Valuation:30:5,Accounting quality:26:0,Balance sheet quality:18:3,Capital structure:24:1,Capital-raising risk:17:0,Cash flow and survival:16:1,Customer economics:16:0,Supply chain:15:0,Intellectual property:12:0,Legal and regulatory:17:0,Geographic and currency risk:11:0,Taxation:9:0,Industry cycle:16:0,Market and macro:33:0,Government and political:25:0,World events:19:0,Company news:22:0,News quality:13:0,Analyst activity:14:2,Institutional activity:12:0,Supply and demand:26:2,Short interest:13:0,Options and positioning:20:0,Technical analysis:29:6,Relative performance:12:0,Social media and sentiment:30:0,Corporate actions:18:0,Red flags (list cut off at 717):3:1".split(',').map(x=>x.split(':'));
const ods=window.deepScan;window.deepScan=function(s){ods(s);const r=D._all.find(x=>x.s==s),p=r.prof||{},h=r.hist||[];let ch='<p class="m">Chart builds as updates run</p>';
 if(h.length>1){const lo=Math.min(...h),hi=Math.max(...h),g=hi-lo||1;ch=`<svg viewBox="0 0 300 120" style="width:100%"><polyline fill="none" stroke="var(--a)" stroke-width="2" points="${h.map((v,i)=>(i/(h.length-1)*300).toFixed(1)+','+(112-(v-lo)/g*100).toFixed(1)).join(' ')}"/><text x="2" y="10" fill="var(--m)" font-size="9">$${hi.toFixed(2)}</text><text x="2" y="118" fill="var(--m)" font-size="9">$${lo.toFixed(2)}</text></svg>`}
 $('db').insertAdjacentHTML('afterbegin',`<div class="al">${ch}<div style="margin-top:6px">${ol(r)}</div><div class="m">Short-term uses today's move, 13-week return, news tone, 52-week position and recent trend. Long-term uses growth, margins, ROE, debt and analysts.</div></div>`);
 $('db').insertAdjacentHTML('afterbegin',tgt(r));$('db').insertAdjacentHTML('afterbegin',verdict(r));const au=XS.reduce((a,x)=>a+ +x[2],0);
 $('db').insertAdjacentHTML('beforeend',`<h3 style="margin:16px 0 4px">Ultimate X-ray (717 points)</h3><div class="m">About ${au} of 717 points are filled automatically. The rest need research.</div><table class="t"><tr><th>Section</th><th>Points</th><th>Auto</th></tr>${XS.map(x=>`<tr><td>${esc(x[0])}</td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join('')}</table><button class="ch" style="margin-top:8px" onclick="cp('Run the Ultimate Stock X-Ray (all 35 sections, 717 points) on ${esc(s)} with current data. Give short-term and long-term outlook, bull/base/bear values and what would invalidate the thesis.')">Copy full X-ray prompt for Claude</button>`)};

const PUBKEY=""; // optional: paste a Finnhub key to scan tickers the site doesn't track (visible to visitors, so use only a free key)
const MX=r=>(r.prof||{}).mx||{};
const FL={price:r=>r.p,chg:r=>r.chg,score:r=>r.score,pe:r=>(r.prof||{}).pe,growth:r=>MX(r).revenueGrowthTTMYoy,epsgrowth:r=>MX(r).epsGrowthTTMYoy,margin:r=>MX(r).netProfitMarginTTM,roe:r=>MX(r).roeTTM,debt:r=>MX(r)['totalDebt/totalEquityQuarterly'],beta:r=>(r.prof||{}).beta,sent:r=>r.sent,sector:r=>r.sec,rating:r=>r.rating,halal:r=>r.halal};
const test=(r,q)=>q.toLowerCase().split(/\s+or\s+/).some(g=>g.split(/\s+and\s+/).every(c=>{const m=c.trim().match(/^(\w+)\s*(<=|>=|=|<|>)\s*(.+)$/);if(!m||!FL[m[1]])throw new Error('Unknown field in: '+c);let a=FL[m[1]](r),b=m[3].trim().replace(/['"]/g,'');if(a==null)return false;if(typeof a=='string')return m[2]=='='&&a.toLowerCase()==b;b=+b;return m[2]=='<'?a<b:m[2]=='>'?a>b:m[2]=='<='?a<=b:m[2]=='>='?a>=b:a==b}));
function runRule(){const o=$('so2');try{const a=D._all.filter(r=>test(r,$('sr').value)).sort((x,y)=>y.score-x.score);o.innerHTML=`<div class="m">${a.length} match${a.length==1?'':'es'}${a.length>60?' (top 60 shown)':''}</div>`+a.slice(0,60).map(mini).join('')}catch(e){o.innerHTML='<span class="dn">'+esc(e.message)+'</span>'}}
async function live(s){const g=p=>fetch(`https://finnhub.io/api/v1/${p}&token=${PUBKEY}`).then(x=>x.json()).catch(()=>null);
 const[q,pr,me,rc,er,it]=await Promise.all([g(`quote?symbol=${s}`),g(`stock/profile2?symbol=${s}`),g(`stock/metric?symbol=${s}&metric=all`),g(`stock/recommendation?symbol=${s}`),g(`stock/earnings?symbol=${s}&limit=4`),g(`stock/insider-transactions?symbol=${s}`)]);
 if(!q||!q.c)return null;const m=(me||{}).metric||{},a=rc&&rc[0],e=Array.isArray(er)?er:[],t=((it||{}).data)||[];
 return{s,p:q.c,chg:q.dp||0,sent:0,news:[],hist:[],halal:'check',sec:'Live',rating:'–',score:0,earn:null,prof:{name:(pr||{}).name||s,ind:(pr||{}).finnhubIndustry||'',hi:m['52WeekHigh'],lo:m['52WeekLow'],pe:m.peTTM,beta:m.beta,mx:m,x:pr||{}},an:a?{strongBuy:a.strongBuy,buy:a.buy,hold:a.hold,sell:a.sell,strongSell:a.strongSell}:null,deep:{n:e.length,beats:e.filter(x=>x.actual>x.estimate).length,sur:e.map(x=>x.surprisePercent),ib:t.filter(x=>x.transactionCode=='P').length,is:t.filter(x=>x.transactionCode=='S').length,peers:[]}}}
async function scan(t){t=(t||'').trim().toUpperCase();if(!t)return;let r=D._all.find(x=>x.s==t);if(!r&&PUBKEY){r=await live(t);if(r)D._all.push(r)}
 if(!r){$('dt').textContent=t;$('db').innerHTML="<p>This ticker isn't tracked yet. Add it to universe.txt on GitHub and it appears after the next update run.</p>";$('dm').style.display='block';return}
 deepScan(t)}
$('q').addEventListener('keydown',e=>{if(e.key=='Enter')scan(e.target.value)});
const X=r=>{const p=r.prof||{},m=MX(r),d=r.deep,pr=r.p,n=v=>v==null?null:v;
 const E=[["ROIC above 10%",n(m.roiTTM)==null?null:m.roiTTM>10],["Operating margin above 10%",n(m.operatingMarginTTM)==null?null:m.operatingMarginTTM>10],["Revenue growth above 15%",n(m.revenueGrowthTTMYoy)==null?null:m.revenueGrowthTTMYoy>15],["Cash generating (P/FCF 0 to 40)",n(m.pfcfShareTTM)==null?null:m.pfcfShareTTM>0&&m.pfcfShareTTM<40],["Liquid (over $1M traded daily)",n(m['10DayAverageTradingVolume'])==null?null:m['10DayAverageTradingVolume']*pr>1],["Beta below 2",n(p.beta)==null?null:p.beta<2],["Within 25% of 52-week high",p.hi?pr>=p.hi*.75:null],["52-week return positive",n(m['52WeekPriceReturnDaily'])==null?null:m['52WeekPriceReturnDaily']>0],["Pays a dividend",n(m.dividendYieldIndicatedAnnual)==null?null:m.dividendYieldIndicatedAnnual>0],["Score 7/10 or higher",r.score>0?r.score>=7:null],["News tone positive",r.news&&r.news.length?r.sent>0:null]];
 const RF=[["Revenue shrinking",m.revenueGrowthTTMYoy!=null&&m.revenueGrowthTTMYoy<0],["Losing money",m.netProfitMarginTTM!=null&&m.netProfitMarginTTM<0],["High debt (D/E above 2)",m['totalDebt/totalEquityQuarterly']>2],["Weak liquidity (current ratio below 1)",m.currentRatioQuarterly<1],["Thin interest coverage (below 1.5)",m.netInterestCoverageTTM<1.5],["Missed estimates 2+ of last 4",d&&d.n&&d.n-d.beats>=2],["Heavy insider selling",d&&d.is>=3&&d.is>=3*Math.max(d.ib,1)],["Penny stock (under $1)",pr<1],["Near 52-week low",p.lo&&pr<=p.lo*1.1],["Analysts lean sell",r.an&&(r.an.sell+r.an.strongSell)>(r.an.strongBuy+r.an.buy)],["Very high valuation (P/S above 20)",m.psTTM>20]];
 return{E,RF:RF.filter(x=>x[1])}};
const verdict=r=>{const x=X(r),a=x.E.filter(e=>e[1]===true).length,b=x.E.filter(e=>e[1]!==null).length,v=x.RF.length>=3?['High caution','dn']:(r.score>=7&&x.RF.length<=1)?['Strong candidate','up']:['Mixed',''];
 return`<div class="al"><b>Screen verdict: <span class="${v[1]}">${v[0]}</span></b><div class="m">Extra screens passed ${a} of ${b} · Red flags ${x.RF.length}</div>${x.RF.map(f=>`<div class="dn" style="font-size:12px">⚠ ${f[0]}</div>`).join('')}<div style="margin-top:6px;font-size:12px">${x.E.map(e=>`<span class="pl ${e[1]===true?'hl':e[1]===false?'hn':''}">${esc(e[0])}</span>`).join('')}</div></div>`};

function hits(){return D?Object.entries(pt).map(([s,v])=>{const r=D._all.find(x=>x.s==s);if(!r)return null;if(v.t&&r.p>=v.t)return[s,'🎯 target $'+v.t+' reached (now $'+r.p.toFixed(2)+')'];if(v.s&&r.p<=v.s)return[s,'🛑 stop $'+v.s+' hit (now $'+r.p.toFixed(2)+')'];return null}).filter(Boolean):[]}
window.savePt=s=>{const t=+$('ptt').value,st=+$('pts').value;if(!t&&!st)delete pt[s];else pt[s]={t:t||0,s:st||0};S('sx_pt',pt);render()};
function tgt(r){const v=pt[r.s]||{};return`<div class="al"><b>🎯 My price targets</b><div class="bar"><input id="ptt" placeholder="Target $" value="${v.t||''}" inputmode="decimal"><input id="pts" placeholder="Stop $" value="${v.s||''}" inputmode="decimal"><button class="ch on" onclick="savePt('${r.s}')">Save</button></div><div class="m">An alert shows at the top of the site when the price reaches either level. Saved on this device only.</div></div>`}
function tbox(){const e=Object.entries(pt);return e.length?`<div class="card" style="margin-bottom:12px"><h3 style="margin:0 0 6px">🎯 Price targets</h3>${e.map(([s,v])=>{const r=D._all.find(x=>x.s==s);return r?`<div class="row mr" data-s="${s}" style="padding:5px 0"><b>${s}</b><span class="m">now $${r.p.toFixed(2)} · target ${v.t?'$'+v.t+' ('+((v.t/r.p-1)*100).toFixed(0)+'%)':'–'} · stop ${v.s?'$'+v.s+' ('+((v.s/r.p-1)*100).toFixed(0)+'%)':'–'}</span></div>`:''}).join('')}</div>`:''}
function heat(){const sc={};D._all.forEach(r=>(sc[r.sec]=sc[r.sec]||[]).push(r.chg));return`<div class="card" style="margin-bottom:12px"><h3 style="margin:0 0 8px">Sector heat map</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:6px">${Object.entries(sc).map(([k,v])=>{const a=v.reduce((x,y)=>x+y,0)/v.length,c=a>=0?'16,185,129':'239,68,68';return`<div style="padding:14px 8px;border-radius:12px;text-align:center;color:#fff;background:rgba(${c},${Math.min(.85,.2+Math.abs(a)/3*.65)})"><b>${esc(k)}</b><div>${a>=0?'+':''}${a.toFixed(2)}%</div><div style="font-size:11px;opacity:.85">${v.length} stocks</div></div>`}).join('')}</div></div>`}
const ml0=V['My list'],ov0=V['Overview'];V['My list']=()=>tbox()+ml0();V['Overview']=()=>heat()+ov0();
})();
